version: '2.1'

services:
  server:
    image: server
    build: ./server
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    volumes:
      - ./server:/usr/src/app
  neo4j:
    image: neo4j-apoc
    build: ./neo4j-apoc
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    # volumes:
      # - $HOME/neo4j/data:/data
    environment: 
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true 
      - NEO4J_apoc_import_file_use__neo4j__config=true 
      